### ISSUE TITLE
如何集成到自己的项目中?

### ISSUE THREAD

**Issue by liaohui5** [nicejade/markdown-online-editor#12]
官方的文档在哪?
怎么安装? 有哪些可配置的props和events?
woc, 这难道不是一个 vue 的组件吗? 还是我太菜了

**Comment by nicejade** [comment]
@liaohui5 这个项目主要是做一个在线编辑器；用了 Vditor 库，官方文档，可以参见： [vditor](https://hacpai.com/tag/vditor?utm_source=nicelinks.site)。如何安装，可以参见上述文档。

本项目不是一个 vue 组件，是一个在线 web 应用。而 Vditor 也不能算是 vue 组件，不过如果你的 vue、react 或其他前端项目想集成，都是可以的。

**Comment by liaohui5** [comment]
大佬, 能否给个example, 不能让我上来就直接研究看源码吧



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "JadeYang(杨琼璞)"<notifications@github.com&gt;; 
发送时间: 2019年12月6日(星期五) 中午11:19
收件人: "nicejade/markdown-online-editor"<markdown-online-editor@noreply.github.com&gt;; 
抄送: "廖辉"<1182468610@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [nicejade/markdown-online-editor] 如何集成到自己的项目中? (#12)




@liaohui5 这个项目主要是做一个在线编辑器；用了 Vditor 库，官方文档，可以参见： vditor。如何安装，可以参见上述文档。
 
本项目不是一个 vue 组件，是一个在线 web 应用。而 Vditor 也不能算是 vue 组件，不过如果你的 vue、react 或其他前端项目想集成，都是可以的。

**Comment by nicejade** [comment]
@liaohui5 如果要看 `Vditor` 是怎么集成到项目中的，可以直接看这 [markdown-online-editor](https://github.com/nicejade/markdown-online-editor/issues/12) 
 项目的；代码片段：[vue use vditor example](https://github.com/nicejade/markdown-online-editor/blob/master/src/pages/Main.vue#L3-L66)。

**Comment by liaohui5** [comment]
好勒, 感谢前辈不吝赐教, 已收藏, 已关注



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "JadeYang(杨琼璞)"<notifications@github.com&gt;; 
发送时间: 2019年12月6日(星期五) 中午11:29
收件人: "nicejade/markdown-online-editor"<markdown-online-editor@noreply.github.com&gt;; 
抄送: "廖辉"<1182468610@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [nicejade/markdown-online-editor] 如何集成到自己的项目中? (#12)




@liaohui5 如果要看 Vditor 是怎么集成到项目中的，可以直接看这 markdown-online-editor
 项目的；代码片段：vue use vditor example。

**Comment by nicejade** [comment]
@liaohui5 👌🤝。
