### ISSUE TITLE
粘贴 HTML 自动转换为 Markdown

### ISSUE THREAD

**Issue by RubiTree** [nicejade/markdown-online-editor#19]
是我的使用姿势不对嘛？尝试了几次没触发自动转换功能呢

比如下面这一段

```
<p>协程这个概念在1958年就开始出现, 目前某些语言开始原生支持(目前主流语言我感觉只有Java完全不支持协程). Java没有原生协程但是可以大型公司都自己或者使用第三方库来支持协程编程, 但是Kotlin原生支持协程.</p>
<p>Android领域的网络请求库一般由Rxjava实现, 包括我自己写的网络请求库同样也是采用的RxJava. 但是这些RxJava实现的网络请求库同样很难方便的实现并发</p>
```

**Comment by nicejade** [comment]
@RubiTree 如果就复制上面👆提到的那段，如果直接在网页上拷贝，则如下图前者，它会被放置在代码块中；如果说只拷贝其中内容字符串，结果会是第二段，可以看到 `p` 标签🏷并没有被渲染出来，说明已经工作了。

这个功能的使用场景比较简单：比如你看到某篇文章值得一读，可以直接 `Ctrl A`、`Ctrl C`，`Ctrl
 V` 至此，就可以体验了。

![粘贴 HTML 自动转换为 Markdown](https://user-images.githubusercontent.com/15773463/71781846-4bf14580-300e-11ea-9c15-467256d13e52.png)

**Comment by RubiTree** [comment]
> @RubiTree 如果就复制上面👆提到的那段，如果直接在网页上拷贝，则如下图前者，它会被放置在代码块中；如果说只拷贝其中内容字符串，结果会是下图👇前者，可以看到 `p` 标签🏷并没有被渲染出来，说明已经工作了。
> 
> 这个功能的使用场景比较简单：比如你看到某篇文章值得一读，可以直接 `Ctrl A`、`Ctrl C`，`Ctrl V` 至此，就可以体验了。
> 
> ![粘贴 HTML 自动转换为 Markdown](https://user-images.githubusercontent.com/15773463/71781846-4bf14580-300e-11ea-9c15-467256d13e52.png)

感谢细致解答，知道用法了~ 赞！
