### ISSUE TITLE
增加「所见即所得」编辑模式

### ISSUE THREAD

**Issue by nicejade** [nicejade/markdown-online-editor#20]
>所见即所得（What you see is what you get，缩写即 WYSIWYG）在编辑器领域指的是看到啥就是啥，比如我想加粗某个字，那“加粗”只是个操作，操作结果就是得到加粗后的文本，而加粗的操作（标记符）是不会出现在文本中的。

>目前看来，大部分人习惯所见即所得的编辑方式，因为这种方式非常直观。但在程序员圈子里却恰恰相反，我们更喜欢标记类排版编辑方式，其中最为流行的是 Markdown。显然这类标记语言不是所见即所得的，但从程序员的角度理解的话，其实这才是真正的所见即所得，就像《黑客帝国》中的代码绿幕。

摘自[ Vditor 所见即所得](https://hacpai.com/article/1577370404903)，作为程序员还是更喜欢标记类排版编辑方式；而且，在 [Arya](https://markdown.lovejade.cn/) 所支持的功能中，大部分用“所见即所得”，并不是那么方便；因此，这里采取默认不是「所见即所得」模式，可以通过在 Toolbar 进行切换。

**Comment by 88250** [comment]
最近已经支持类似 Typora 的*即时渲染*编辑模式了，可以考虑同步一波。

![vditor-ir](https://img.hacpai.com/file/2020/03/ir-6d784c1f.gif)

**Comment by nicejade** [comment]
@88250 事实上这边已经尝试同步了几次了，**开发环境**没有任何问题；但，一旦打正式环境的包，渲染就会出现问题；还没定位出问题所在（也许是这边使用姿势存在问题），所以还没反馈呢。

**Comment by 88250** [comment]
有问题可以随时找 @Vanessa219，就在这个 issue 中交流就行，说不定是 Vditor 的问题 😂

**Comment by nicejade** [comment]
已在 [Arya Markdown 最新版本](https://markdown.lovejade.cn/)中，更新 Vditor 至 v3.1.12， 使得拥有了**「所见即所得」**编辑模式；处于一些原因考虑，默认并未采用这种模式，您可以通过操作、后者快捷键切换到这种模式：`⌘-⌥-7`（`Ctrl-alt-7`）；祝能所有人可以使用的很开心。
