### ISSUE TITLE
导出PDF什么时候才能完成啊

### ISSUE THREAD

**Issue by will-mei** [nicejade/markdown-online-editor#25]
现在就只能在线预览啊, 还不具有实际使用能力, 没法导出, 怎么发布内容呢.

**Comment by nicejade** [comment]
@will-mei 导出 PDF 功能是存在的呢（虽然不尽完美，在导出冗杂有图表和文本时候），点击右上角设置按钮，即可看到导出 PDF 等功能入口。

**Comment by will-mei** [comment]
可能也是兼容性的问题吧, 我用的是 FireFox,  >_<

**Comment by nicejade** [comment]
@will-mei 喔，刚才用 FireFox 尝试了下，可以工作；不过导出的 PDF 也并不完美（暂时，可以先手动去除页面顶部不需要的 header 以及导出按钮，启用浏览器自带的导出 PDF 功能，予以替代）；后面要优化下。
![markdown-online-editor PDF 导出](https://user-images.githubusercontent.com/15773463/75659532-1a5ec880-5ca5-11ea-8daa-c30dffd75a2f.png)

**Comment by choora** [comment]
> @will-mei 喔，刚才用 FireFox 尝试了下，可以工作；不过导出的 PDF 也并不完美（暂时，可以先手动去除页面顶部不需要的 header 以及导出按钮，启用浏览器自带的导出 PDF 功能，予以替代）；后面要优化下。
> ![markdown-online-editor PDF 导出](https://user-images.githubusercontent.com/15773463/75659532-1a5ec880-5ca5-11ea-8daa-c30dffd75a2f.png)

请问为什么我点击「生成导出」为什么毫无反应呢？无论是选择 PNG、JPEG 还是 PDF 格式，都没有反应？使用的浏览器是 Chrome。

**Comment by nicejade** [comment]
@choora  请参见如下截图，您可以使用这种方式，来导出 PDF 以及 Markdown 或 HTML 等。

![image](https://user-images.githubusercontent.com/15773463/98431186-069a1a80-20ee-11eb-8381-b804c5dab6da.png)
