### ISSUE TITLE
粘贴CSDN的文章不支持html转md

### ISSUE THREAD

**Issue by codingcn** [nicejade/markdown-online-editor#27]
试了别的网站是ok的，就csdn不行

**Comment by nicejade** [comment]
@codingcn 因为这个网站（可以说是很不厚道的，因为其中内容多半是抄袭，却不想让其他人拷贝，而且体验非常不好），对「复制」做了处理，使得剪切版中的内容只是文本，而不是 html，也就无法转成 md 了；拒绝使用 CSDN 是程序员更加明智的抉择。
