### ISSUE TITLE
导出微信公众号格式

### ISSUE THREAD

**Issue by jixiang-wang** [nicejade/markdown-online-editor#29]
大佬，什么能完成markdown转微信公众号的功能？

**Comment by nicejade** [comment]
@jixiang-wang 原本是想做来着，后面看到已经有人做出了一些很好用的工具了，如[让微信排版变 Nice](https://nicelinks.site/post/5e0a21d616bdad16b0f5b1fb)；所以就没打算做重复的功能了；请问，如果已知这样的工具，您觉得需要在这个工具中集成以下么（可以根据大家的诉求，再考量下）？

**Comment by jixiang-wang** [comment]
个人觉得，还是集中一下吧！就是写完markdown，直接点击你这个转为微信公众号格式，开通你这个图床后，然后直接复制粘贴到微信编辑里，就不用再去调整格式的那种，懂了吗？就是图片能直接在微信里用的，不用再去手动上传的，还是就是你们是把图片上传到微信图床吗？微信图床最大是100张吗？超过100张之后怎么办？ 希望能尽快更新版本吧！ 王吉祥 邮箱：wjx411527@gmail.com 签名由 网易邮箱大师 定制 在2020年04月18日 10:42，JadeYang(杨琼璞) 写道： @jixiang-wang 原本是想做来着，后面看到已经有人做出了一些很好用的工具了，如让微信排版变 Nice；所以就没打算做重复的功能了；请问，如果已知这样的工具，您觉得需要在这个工具中集成以下么（可以根据大家的诉求，再考量下）？ — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by 88250** [comment]
[Vditor 正准备支持复制粘贴到微信公众号](https://github.com/Vanessa219/vditor/issues/325)，开发完毕可以考虑同步一波 😄

**Comment by nicejade** [comment]
@88250 赞耶，期待。

**Comment by nicejade** [comment]
@jixiang-wang 已收到；点击转化为「微信公众号格式」，后面同步下 [Vditor](https://github.com/Vanessa219/vditor/issues/325) 最新版即可。然后，将图片上传到微信图床，这个微信公众号这边不知提供 api 了没耶，如果有，应该也需要关联账号的吧。

**Comment by 88250** [comment]
只要在用的图床允许跨站访问（不开防盗链），微信公众号的编辑器会自动拉取图片的，所以我认为主动上传微信其实并不是那么常用。

**Comment by nicejade** [comment]
@88250 喔，这个倒没怎么注意，如果可以拉取到，确实可以不用上传⏫到微信图床。
