### ISSUE TITLE
怎么集成到个人网站？

### ISSUE THREAD

**Issue by qiankeqin** [nicejade/markdown-online-editor#30]
你好，作者。
这个markdown怎么才能集成到个人网站上？

**Comment by nicejade** [comment]
@qiankeqin 如果是要集成到个人网站，最好是直接使用 [@Vanessa219](https://github.com/Vanessa219/) 所提供的 [vditor](https://github.com/Vanessa219/vditor) 库（有详细文档）；现在这个编辑器，基本都是用 `vditor` 所提供的功能，做了点扩展，部署了下而已。

**Comment by code-farmer-i** [comment]
> 你好，作者。
> 这个markdown怎么才能集成到个人网站上？

试试这个[v-md-editor](https://code-farmer-i.github.io/vue-markdown-editor/senior/toc.html)

**Comment by 88250** [comment]
@code-farmer-i 你如果不能解决楼主的问题就不要回复。

通过到其他类似项目下回复来给自己的项目引流是一种低劣的推广手段，请保持对其他开源贡献者基本的礼貌。
