### ISSUE TITLE
怎么导出HTML呢？

### ISSUE THREAD

**Issue by Aaron-leo** [nicejade/markdown-online-editor#34]
发现没法导出HTML文件，请问可以导出吗？

**Comment by nicejade** [comment]
@Aaron-leo 

![Arya Markdown 导出 HTML](https://user-images.githubusercontent.com/15773463/84616280-22faa800-aefe-11ea-9db0-58f52603ee17.png)

**Comment by Aaron-leo** [comment]
好的，谢谢啦

**Comment by Aaron-leo** [comment]
诶呀！图片看不到呀！

**Comment by nicejade** [comment]
@Aaron-leo 请问是看不到我回复的图片么？

**Comment by Aaron-leo** [comment]
是的呢，我看不到你回复的图片，打不开


| |
aaron_leo7
|
|
aaron_leo7@163.com
|
签名由网易邮箱大师定制
在2020年7月8日 21:10，JadeYang(杨琼璞)<notifications@github.com> 写道：

Closed #34.

**Comment by nicejade** [comment]
可能是 `camo.githubusercontent.com` 这个域名在某些网络下不能被正常访问所致，已经重新上传图床。见下图：
![arya markdown 导出 html](https://i.loli.net/2020/09/23/qRUlnQr9MmwA6O8.png)

**Comment by Aaron-leo** [comment]
确实，我发现是因为这个域名在我这里不能正常访问，我尝试换了好几个网络都不行。感谢回复。

**Comment by nicejade** [comment]
@Aaron-leo 想必是需要科(F)学(Q)上网才可以，客气客气。
