### ISSUE TITLE
想用，但是不能通过npm安装吗

### ISSUE THREAD

**Issue by smally84** [nicejade/markdown-online-editor#4]

**Comment by nicejade** [comment]
@smally84 嗨，您好。这里是根据 [vditor](https://github.com/b3log/vditor)，结合一些其他工具，如 `vue` 等所构建的一个**在线 IDE**，以供大家使用。

如果您想通过 `npm` 来安装，猜测您可能是想在项目中使用，推荐您直接使用 [vditor](https://github.com/b3log/vditor) 即可。

**Comment by smally84** [comment]
好的，谢谢了

**Comment by nicejade** [comment]
@smally84 🤝🤝
