### ISSUE TITLE
请问在即时渲染模式下可以设置像typora那样按特定快捷键才会显示markdown源码吗？

### ISSUE THREAD

**Issue by luhggit** [nicejade/markdown-online-editor#45]
首先感谢作者大大创造了这么优秀的作品，非常好用，感谢感谢！

然后，我想问一下，能不能实现这样一个功能：

在即时渲染的模式下，当光标移动有markdown标签的地方，不会马上显示markdown源码，而是像typora一样只有按快捷键才会显示

或者，把光标移上去显示源码做成一个开关，按特定快捷键可以进行开闭

当然，如果作者大大不方便修改的话，可以指示一下对应的源码位置吗，我可以自己研究一下改一下

**Comment by nicejade** [comment]
没关系，🤝。
