### ISSUE TITLE
能不能搞个docker版的？

### ISSUE THREAD

**Issue by troray** [nicejade/markdown-online-editor#59]
能够方便快速的部署个在线版的

**Comment by cqboyone** [comment]
同问

**Comment by nicejade** [comment]
@troray @cqboyone   其实，本项目已经非常方便在线部署了呢。具体步骤如下：

1. Fork 项目；
2. 修改 [deploy.sh#L13](https://github.com/nicejade/markdown-online-editor/blob/master/commands/deploy.sh#L13)；
  即，修改这句即可：echo 'markdown.lovejade.cn' > CNAME，以及 push 地址。
3. 克隆至本地，运行 `yarn deploy` 命令；
4. 打开 YOUR_NAME.gitlab.io 地址即可（基于 Github Pages，自定义域名，需要配置 CNAME）；

大致是这样，细节上略有出入。当然，如果自己服务器，同样也很方便，只需要构建产物，然后 域名 及Nginx 即可。

**Comment by kingname** [comment]
@nicejade 实际上并没有那么方便。因为yarn 安装的时候，依赖问题其实比较麻烦。

1. 直接在Linux上安装，并且没有安装chromium，系统没有chrome的话，那么启动不起来。
2. 手动安装chromium以后，因为Linux机器没有图形界面，也启动不起来
3. 可能会提示缺少libssn3

**Comment by nicejade** [comment]
@kingname 嗯，这可能是项目设定没有完全修改所致？在后面的设计中，不再引入 prerender-spa-plugin 来解决预渲染问题；按道理不该存在 chromium 安装问题呢。如果仍存在，可讲 prerender-spa-plugin 相关依赖，直接做删除处理即可。

这边会抽空尽快检查下，以做修复。当然，做一个 docker 版本，来方便快速的部署个在线版，是个很棒的建议：）。

**Comment by nicejade** [comment]
@kingname  在最新的修改中，已经移除 [prerender-spa-plugin](https://github.com/nicejade/markdown-online-editor/commit/1d0a6b3aefdd6308642192d16179690134592fb2) 这个插件，那么可以基于 npm / yarn，轻松构建并部署在后台，而不会遇到依赖安装问题。

**Comment by nicejade** [comment]
@troray @cqboyone @kingname  已将最新版本使用 [Docker](https://nicelinks.site/post/5b7036890f8719053c094d68) 打包镜像并上传至 [Docker Hub](https://hub.docker.com/r/nicejade/markdown-online-editor)，可通过如下方式进行使用：

```bash
docker run -d -p [Your-Specified-Port]:80 nicejade/markdown-online-editor

# Eg：

docker run -d -p 8866:80 nicejade/markdown-online-editor
```

如果您在本地执行，只需打开网址 http://localhost:8866 即可访问。如果在服务器运行，可以通过 http://[Server-IP]:8866 来访问，如果要配备域名，可通过。
