### ISSUE TITLE
怎么在本地部署

### ISSUE THREAD

**Issue by liu-blog** [nicejade/markdown-online-editor#75]
怎么在本地部署

**Comment by nicejade** [comment]
@liu-blog 

运行如下两步命令即可：

```
# install 
yarn 
# build
yarn build
# lanuch local server
npx arya-jarvis s
```
当然，最后一步启动本地静态服务，可以有很多方法，具体可参见：[快速搭建 HTTP 静态服务的 10 种方法](https://quickapp.lovejade.cn/10-ways-to-quickly-build-http-static-services/)。
